feat/settings
MCN-ING/ing-verif pull request #60
Opened 2023-03-17 17:56 UTC by agueye84

<img width="483" alt="image" src="https://user-images.githubusercontent.com/120060804/225982073-a6067d1d-4b01-4f77-91b6-a666cb283daf.png">

2023-03-17 18:49 UTC, jcdrouin21 commented on src/components/LanguageSelector.tsx
> +  const { t } = useTranslation();
Si tu as vraiment besoin des deux `const { i18n, t } = useTranslation()`

2023-03-17 18:55 UTC, jcdrouin21 commented on src/localization/fr/index.ts
> +    Title: 'Gouvernement de Quèbec',
Québec

2023-03-17 19:17 UTC, fc-santos commented on src/components/AppSettingItem.tsx
> +      state.langueApp = languageList[index].label
Ceci n'est pas une bonne pratique. Il faut utiliser un dispatch pour apporter des modifications dans le state.

2023-03-17 19:29 UTC, fc-santos requested changes

2023-03-17 19:29 UTC, fc-santos commented on src/components/AppSettingItem.tsx
> +      state.langueApp = languageList[index].label
Ceci n'est pas une bonne pratique. Il faut utiliser un dispatch pour apporter des modifications dans le state.

2023-03-17 19:29 UTC, fc-santos commented on src/components/HistoricSelector.tsx
> +    state.history = id
Idem ici pour le state

2023-03-17 19:29 UTC, fc-santos commented on src/components/LanguageSelector.tsx
> +    state.langueApp = languageList[index].label
idem ici pour le state

2023-03-17 19:29 UTC, fc-santos commented on src/components/LanguageSelector.tsx
> +    state.langueApp = languageList[index].label
Et ici

2023-03-20 12:49 UTC, jcdrouin21 commented on src/assets/HistoricList.ts
> +    ]
J'aime pas l'utilisation des id pour référer le temps du lookback (sauvegarder la sélection). Peut-être mettre un `type`, `const` ou  autre chose qui fait plus de sens.

2023-03-20 12:50 UTC, jcdrouin21 commented on src/assets/LanguageList.ts
> +            label: t('LanguageList.Title1'),
Messemble `LanguageList.English` et `LanguageList.French` parlerait plus que `Title1` et `Title2`

2023-03-20 12:54 UTC, jcdrouin21 commented on src/assets/SettingsList.ts
> +      route : 'ContactUs'
Même chose `Title1`, `Title2`, etc. ne veut rien dire sur le contenu. Utilise des choses qui parlent ex: `SettingsList.ContactUs`

2023-03-20 12:55 UTC, jcdrouin21 commented on src/assets/AboutList.ts
> +    },
Idem

2023-03-20 12:55 UTC, jcdrouin21 commented on src/assets/AppSettingList.ts
> +    },
Idem

2023-03-20 12:56 UTC, jcdrouin21 commented on src/assets/ContactUsList.ts
> +    },
Idem

2023-03-20 12:56 UTC, jcdrouin21 commented on src/assets/HelpCenterList.ts
> +      route: 'ImproveApp',
Idem

2023-03-20 12:56 UTC, jcdrouin21 commented on src/assets/HistoricList.ts
> +        },
Idem

2023-03-20 13:08 UTC, jcdrouin21 commented on src/components/HistoricSelector.tsx
> +const HistoricSelector = () => {
Je ne pense pas que `Historic` est le bon mot. (Il est répéter beaucoup ici)

2023-03-20 13:10 UTC, jcdrouin21 commented on src/components/HistoricSelector.tsx
> +  }, [state.history])
Pourquoi on set le default ici et pas directement dans le `store`?

2023-03-20 13:36 UTC, jcdrouin21 commented on src/components/AppSettingItem.tsx
> +          ) : null}
{ navigate && <View>...</View>} ?

2023-03-20 18:52 UTC, agueye84 commented on src/components/LanguageSelector.tsx
> +}
ca s'est glissé dans le code. C'est a enlever

2023-03-21 13:31 UTC, jcdrouin21 commented on package.json
> +    "react-native-version-number": "^0.3.6",
Ça ne va pas chercher le vrai version de l'application ?

2023-03-21 13:34 UTC, jcdrouin21 commented on src/components/SettingItem.tsx
> +      <View style={[styles.settingCard, {flex: 2}]}>
Si tu définis le style `settingCard` et qu'il est utilisé seulement ici pourquoi ne pas mettre `flex:2` directement dedans `style.settingCard` ?

2023-03-21 13:36 UTC, jcdrouin21 commented on src/components/SettingItem.tsx
> +        <Text style={[defaultStyles.text, styles.settingTitle, styles.textManaged]}>{item.title}</Text>
Même principe ici. Si `styles.settingTitle` et `styles.textManaged` sont seulement utilisés ici, pourquoi pas les mettre ensemble ?

2023-03-21 13:41 UTC, jcdrouin21 commented on src/navigators/RootStack.tsx
> +      />
Au nombre de page qu'il y a dans les setting, j'aurais créé une nouvelle stack juste pour les settings...

2023-03-21 13:44 UTC, jcdrouin21 commented on src/screens/About.tsx
> +          return <AppSettingItem key={index.toString()} item={item} action={() => handleSelection(item)} />
Tous les items de about ont des uuid. pourquoi ne pas les utiliser comme key à la place de l'index. C'est mieux et tu les as déjà...

2023-03-21 13:48 UTC, jcdrouin21 commented on src/screens/HelpCenter.tsx
> +        })}
Idem

2023-03-21 13:48 UTC, jcdrouin21 commented on src/screens/Settings.tsx
> +        })}
Idem

2023-03-22 12:11 UTC, jcdrouin21 approved these changes

2023-03-22 14:19 UTC, fc-santos requested changes

2023-03-22 14:19 UTC, fc-santos commented on src/components/LanguageSelector.tsx
> +    i18n.changeLanguage(code)
Je déplacerais peut-être l'appel à cette fonction à l'intérieur du store dans le dispatch.

2023-03-22 14:51 UTC, fc-santos approved these changes

2023-03-22 15:48 UTC, merged